In [1]:
import numpy as np
import torch
import torch.nn.functional as F
from torch.autograd import Variable

In [2]:
N = 100
D = 2

In [3]:
X = np.random.randn(N,D)*2

In [4]:
# center the first N/2 points at (-2,-2)
X[:int(N / 2), :] = X[:int(N / 2), :] - 2 * np.ones((int(N / 2), D))

# center the last N/2 points at (2, 2)
X[int(N / 2):, :] = X[int(N / 2):, :] + 2 * np.ones((int(N / 2), D))

# labels: first N/2 are 0, last N/2 are 1
T = np.array([0] * int(N / 2) + [1] * int(N / 2)).reshape(100, 1)

In [5]:
x_data = Variable(torch.Tensor(X))
y_data = Variable(torch.Tensor(T))

In [6]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = torch.nn.Linear(2, 1) # 2 in and 1 out
        
    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred
    
# Our model    
model = Model()

In [7]:
criterion = torch.nn.BCELoss(size_average=True)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

/usr/local/lib/python2.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))


In [8]:
# Training loop
for epoch in range(1000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)
    
    # Compute and print loss
    loss = criterion(y_pred, y_data)
    print(epoch, loss.data[0])
    
    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

/usr/local/lib/python2.7/site-packages/ipykernel_launcher.py:8: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  


(0, tensor(2.1858))
(1, tensor(2.1297))
(2, tensor(2.0742))
(3, tensor(2.0193))
(4, tensor(1.9651))
(5, tensor(1.9117))
(6, tensor(1.8590))
(7, tensor(1.8071))
(8, tensor(1.7560))
(9, tensor(1.7058))
(10, tensor(1.6564))
(11, tensor(1.6080))
(12, tensor(1.5606))
(13, tensor(1.5142))
(14, tensor(1.4688))
(15, tensor(1.4244))
(16, tensor(1.3812))
(17, tensor(1.3391))
(18, tensor(1.2981))
(19, tensor(1.2583))
(20, tensor(1.2197))
(21, tensor(1.1823))
(22, tensor(1.1462))
(23, tensor(1.1112))
(24, tensor(1.0775))
(25, tensor(1.0450))
(26, tensor(1.0138))
(27, tensor(0.9837))
(28, tensor(0.9549))
(29, tensor(0.9272))
(30, tensor(0.9007))
(31, tensor(0.8754))
(32, tensor(0.8511))
(33, tensor(0.8280))
(34, tensor(0.8059))
(35, tensor(0.7848))
(36, tensor(0.7647))
(37, tensor(0.7455))
(38, tensor(0.7272))
(39, tensor(0.7098))
(40, tensor(0.6932))
(41, tensor(0.6774))
(42, tensor(0.6624))
(43, tensor(0.6480))
(44, tensor(0.6344))
(45, tensor(0.6214))
(46, tensor(0.6089))
(47, tensor(0.5971))
(4

(655, tensor(0.2077))
(656, tensor(0.2077))
(657, tensor(0.2077))
(658, tensor(0.2077))
(659, tensor(0.2076))
(660, tensor(0.2076))
(661, tensor(0.2076))
(662, tensor(0.2076))
(663, tensor(0.2075))
(664, tensor(0.2075))
(665, tensor(0.2075))
(666, tensor(0.2075))
(667, tensor(0.2074))
(668, tensor(0.2074))
(669, tensor(0.2074))
(670, tensor(0.2074))
(671, tensor(0.2073))
(672, tensor(0.2073))
(673, tensor(0.2073))
(674, tensor(0.2073))
(675, tensor(0.2073))
(676, tensor(0.2072))
(677, tensor(0.2072))
(678, tensor(0.2072))
(679, tensor(0.2072))
(680, tensor(0.2071))
(681, tensor(0.2071))
(682, tensor(0.2071))
(683, tensor(0.2071))
(684, tensor(0.2070))
(685, tensor(0.2070))
(686, tensor(0.2070))
(687, tensor(0.2070))
(688, tensor(0.2070))
(689, tensor(0.2069))
(690, tensor(0.2069))
(691, tensor(0.2069))
(692, tensor(0.2069))
(693, tensor(0.2068))
(694, tensor(0.2068))
(695, tensor(0.2068))
(696, tensor(0.2068))
(697, tensor(0.2068))
(698, tensor(0.2067))
(699, tensor(0.2067))
(700, tens

In [9]:
w = np.array([])
for f in model.parameters():
    print('data is')
    print(f.data)
    print(f.grad)

data is
tensor([[0.9169, 0.9204]])
tensor([[-0.0209, -0.0191]])
data is
tensor([-0.2480])
tensor([-0.0018])


In [10]:
w = list(model.parameters())

In [11]:
w0 = w[0].data.numpy()

In [12]:
w1 = w[1].data.numpy()

In [13]:
import matplotlib.pyplot as plt

print("Final gradient descend:", w)
# plot the data and separating line
plt.scatter(X[:,0], X[:,1], c=T.reshape(N), s=100, alpha=0.5)
x_axis = np.linspace(-6, 6, 100)
y_axis = -(w1[0] + x_axis*w0[0][0]) / w0[0][1]
line_up, = plt.plot(x_axis, y_axis,'r--', label='gradient descent')
plt.legend(handles=[line_up])
plt.xlabel('X(1)')
plt.ylabel('X(2)')
plt.show()

('Final gradient descend:', [Parameter containing:
tensor([[0.9169, 0.9204]], requires_grad=True), Parameter containing:
tensor([-0.2480], requires_grad=True)])
